/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.artefato.sprint;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Renan
 */
public class MedicaoComponentes extends javax.swing.JFrame {

    /**
     * Creates new form MedicaoComponentes
     */
    public MedicaoComponentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBackground = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        prgDISK = new javax.swing.JProgressBar();
        lblDISKpercent = new javax.swing.JLabel();
        lblDISK = new javax.swing.JLabel();
        prgRAM = new javax.swing.JProgressBar();
        lblRAM = new javax.swing.JLabel();
        lblRAMpercent = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        lblCPUpercent = new javax.swing.JLabel();
        prgCPU = new javax.swing.JProgressBar();
        lblMaxCPU = new javax.swing.JLabel();
        lblMaxNumberCPU = new javax.swing.JLabel();
        lblMinCPU = new javax.swing.JLabel();
        lblMinNumberCPU = new javax.swing.JLabel();
        lblMediaCPU = new javax.swing.JLabel();
        lblMediaNumberCPU = new javax.swing.JLabel();
        lblMaxRAM = new javax.swing.JLabel();
        lblMaxNumberRAM = new javax.swing.JLabel();
        lblMediaRAM = new javax.swing.JLabel();
        lblMediaNumberRAM = new javax.swing.JLabel();
        lblMinRAM = new javax.swing.JLabel();
        lblMinNumberRAM = new javax.swing.JLabel();
        lblMediaNumberDISK = new javax.swing.JLabel();
        lblMinNumberDISK = new javax.swing.JLabel();
        lblMinDISK = new javax.swing.JLabel();
        lblMediaDISK = new javax.swing.JLabel();
        lblMaxNumberDISK = new javax.swing.JLabel();
        lblMaxDISK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelBackground.setBackground(new java.awt.Color(16, 33, 70));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(245, 245, 245));
        jButton1.setText("Fazer leituras de dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblDISKpercent.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblDISKpercent.setForeground(new java.awt.Color(245, 245, 245));
        lblDISKpercent.setText("0");

        lblDISK.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblDISK.setForeground(new java.awt.Color(245, 245, 245));
        lblDISK.setText("DISCO:");

        lblRAM.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblRAM.setForeground(new java.awt.Color(245, 245, 245));
        lblRAM.setText("Memória RAM:");

        lblRAMpercent.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblRAMpercent.setForeground(new java.awt.Color(245, 245, 245));
        lblRAMpercent.setText("0");

        lblCPU.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblCPU.setForeground(new java.awt.Color(245, 245, 245));
        lblCPU.setText("CPU:");

        lblCPUpercent.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblCPUpercent.setForeground(new java.awt.Color(245, 245, 245));
        lblCPUpercent.setText("0");

        lblMaxCPU.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblMaxCPU.setForeground(new java.awt.Color(245, 245, 245));
        lblMaxCPU.setText("Máximo:");

        lblMaxNumberCPU.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMaxNumberCPU.setForeground(new java.awt.Color(245, 245, 245));
        lblMaxNumberCPU.setText("0");

        lblMinCPU.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblMinCPU.setForeground(new java.awt.Color(245, 245, 245));
        lblMinCPU.setText("Mínimo:");

        lblMinNumberCPU.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMinNumberCPU.setForeground(new java.awt.Color(245, 245, 245));
        lblMinNumberCPU.setText("0");

        lblMediaCPU.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblMediaCPU.setForeground(new java.awt.Color(245, 245, 245));
        lblMediaCPU.setText("Média:");

        lblMediaNumberCPU.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMediaNumberCPU.setForeground(new java.awt.Color(245, 245, 245));
        lblMediaNumberCPU.setText("0");

        lblMaxRAM.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblMaxRAM.setForeground(new java.awt.Color(245, 245, 245));
        lblMaxRAM.setText("Máximo:");

        lblMaxNumberRAM.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMaxNumberRAM.setForeground(new java.awt.Color(245, 245, 245));
        lblMaxNumberRAM.setText("0");

        lblMediaRAM.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblMediaRAM.setForeground(new java.awt.Color(245, 245, 245));
        lblMediaRAM.setText("Média:");

        lblMediaNumberRAM.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMediaNumberRAM.setForeground(new java.awt.Color(245, 245, 245));
        lblMediaNumberRAM.setText("0");

        lblMinRAM.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblMinRAM.setForeground(new java.awt.Color(245, 245, 245));
        lblMinRAM.setText("Mínimo:");

        lblMinNumberRAM.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMinNumberRAM.setForeground(new java.awt.Color(245, 245, 245));
        lblMinNumberRAM.setText("0");

        lblMediaNumberDISK.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMediaNumberDISK.setForeground(new java.awt.Color(245, 245, 245));
        lblMediaNumberDISK.setText("0");

        lblMinNumberDISK.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMinNumberDISK.setForeground(new java.awt.Color(245, 245, 245));
        lblMinNumberDISK.setText("0");

        lblMinDISK.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblMinDISK.setForeground(new java.awt.Color(245, 245, 245));
        lblMinDISK.setText("Mínimo:");

        lblMediaDISK.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblMediaDISK.setForeground(new java.awt.Color(245, 245, 245));
        lblMediaDISK.setText("Média:");

        lblMaxNumberDISK.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblMaxNumberDISK.setForeground(new java.awt.Color(245, 245, 245));
        lblMaxNumberDISK.setText("0");

        lblMaxDISK.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblMaxDISK.setForeground(new java.awt.Color(245, 245, 245));
        lblMaxDISK.setText("Máximo:");

        javax.swing.GroupLayout painelBackgroundLayout = new javax.swing.GroupLayout(painelBackground);
        painelBackground.setLayout(painelBackgroundLayout);
        painelBackgroundLayout.setHorizontalGroup(
            painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBackgroundLayout.createSequentialGroup()
                        .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prgRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelBackgroundLayout.createSequentialGroup()
                                .addComponent(lblRAM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRAMpercent)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBackgroundLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBackgroundLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(106, 106, 106))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBackgroundLayout.createSequentialGroup()
                                .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prgDISK, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelBackgroundLayout.createSequentialGroup()
                                        .addComponent(lblDISK)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDISKpercent)))
                                .addContainerGap())))
                    .addGroup(painelBackgroundLayout.createSequentialGroup()
                        .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelBackgroundLayout.createSequentialGroup()
                                .addComponent(lblMaxCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMaxNumberCPU)
                                .addGap(80, 80, 80)
                                .addComponent(lblMediaCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMediaNumberCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMinCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMinNumberCPU))
                            .addGroup(painelBackgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prgCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelBackgroundLayout.createSequentialGroup()
                                        .addComponent(lblCPU)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCPUpercent))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBackgroundLayout.createSequentialGroup()
                                .addComponent(lblMaxRAM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMaxNumberRAM)
                                .addGap(80, 80, 80)
                                .addComponent(lblMediaRAM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMediaNumberRAM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMinRAM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMinNumberRAM))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBackgroundLayout.createSequentialGroup()
                                .addComponent(lblMaxDISK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMaxNumberDISK)
                                .addGap(80, 80, 80)
                                .addComponent(lblMediaDISK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMediaNumberDISK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMinDISK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMinNumberDISK)))
                        .addContainerGap())))
        );
        painelBackgroundLayout.setVerticalGroup(
            painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPU)
                    .addComponent(lblCPUpercent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxCPU)
                    .addComponent(lblMinCPU)
                    .addComponent(lblMediaCPU)
                    .addComponent(lblMaxNumberCPU)
                    .addComponent(lblMediaNumberCPU)
                    .addComponent(lblMinNumberCPU))
                .addGap(40, 40, 40)
                .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRAM)
                    .addComponent(lblRAMpercent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxRAM)
                    .addComponent(lblMinRAM)
                    .addComponent(lblMediaRAM)
                    .addComponent(lblMaxNumberRAM)
                    .addComponent(lblMediaNumberRAM)
                    .addComponent(lblMinNumberRAM))
                .addGap(40, 40, 40)
                .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDISK)
                    .addComponent(lblDISKpercent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgDISK, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(painelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxDISK)
                    .addComponent(lblMinDISK)
                    .addComponent(lblMediaDISK)
                    .addComponent(lblMaxNumberDISK)
                    .addComponent(lblMediaNumberDISK)
                    .addComponent(lblMinNumberDISK))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        //CPU        
        Integer valorMaximoCPU = 0;
        Integer valorMinimoCPU = 0;
        Integer valorMediaCPU = 0;
        Integer mediaAtualizadaCPU = 0;
        
        //RAM        
        Integer valorMaximoRAM = 0;
        Integer valorMinimoRAM = 0;
        Integer valorMediaRAM = 0;
        Integer mediaAtualizadaRAM = 0;
        
        //DISK        
        Integer valorMaximoDISK = 0;
        Integer valorMinimoDISK = 0;
        Integer valorMediaDISK = 0;
        Integer mediaAtualizadaDISK = 0;
        
        
        Integer rodada = 0;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        rodada++;
        
        //Random CPU
        Integer randomCPU = ThreadLocalRandom.current().nextInt(0,101);
        lblCPUpercent.setText(randomCPU.toString() + "%");
        prgCPU.setValue(randomCPU);
        
        //Comparação de valores CPU (MAX, MIN, AVG)
        //Primeira leitura
        if (rodada == 1) {
            valorMaximoCPU = randomCPU;
            lblMaxNumberCPU.setText(valorMaximoCPU.toString() + "%");
            
            valorMinimoCPU = randomCPU;
            lblMinNumberCPU.setText(valorMinimoCPU.toString() + "%");
        } else { //Demais leituras
            if (randomCPU > valorMaximoCPU) {
                valorMaximoCPU = randomCPU;
                lblMaxNumberCPU.setText(valorMaximoCPU.toString() + "%");
            } else if (randomCPU < valorMinimoCPU) {
                valorMinimoCPU = randomCPU;
                lblMinNumberCPU.setText(valorMinimoCPU.toString() + "%");
            }  
        }
        
        //MediaCPU
        valorMediaCPU = (randomCPU + valorMediaCPU);
        mediaAtualizadaCPU = valorMediaCPU/ rodada;
        lblMediaNumberCPU.setText(mediaAtualizadaCPU.toString() + "%");

        //Random RAM
        Integer randomRAM = ThreadLocalRandom.current().nextInt(0,101);
        lblRAMpercent.setText(randomRAM.toString() + "%");
        prgRAM.setValue(randomRAM);
        
        //Comparação de valores RAM (MAX, MIN, AVG)
        //Primeira leitura
        if (rodada == 1) {
            valorMaximoRAM = randomRAM;
            lblMaxNumberRAM.setText(valorMaximoRAM.toString() + "%");
            
            valorMinimoRAM = randomRAM;
            lblMinNumberRAM.setText(valorMinimoRAM.toString() + "%");
        } else { //Demais Leituas
            if (randomRAM > valorMaximoRAM) {
                valorMaximoRAM = randomRAM;
                lblMaxNumberRAM.setText(valorMaximoRAM.toString() + "%");
            } else if (randomRAM < valorMinimoRAM) {
                valorMinimoRAM = randomRAM;
                lblMinNumberRAM.setText(valorMinimoRAM.toString() + "%");
            }
        }
        
        //MediaRAM
        valorMediaRAM = (randomRAM + valorMediaRAM);
        mediaAtualizadaRAM = valorMediaRAM/ rodada;
        lblMediaNumberRAM.setText(mediaAtualizadaRAM.toString() + "%");
        
        //Random DISCO
        Integer randomDISK = ThreadLocalRandom.current().nextInt(0,101);
        lblDISKpercent.setText(randomDISK.toString() + "%");
        prgDISK.setValue(randomDISK);
        
        //Comparação de valores DISCO (MAX, MIN, AVG)
        //Primeira leitura
        if (rodada == 1) {
            valorMaximoDISK = randomDISK;
            lblMaxNumberDISK.setText(valorMaximoDISK.toString() + "%");
            
            valorMinimoDISK = randomDISK;
            lblMinNumberDISK.setText(valorMinimoDISK.toString() + "%");
        } else { //Demais leituras
            if (randomDISK > valorMaximoDISK) {
                valorMaximoDISK = randomDISK;
                lblMaxNumberDISK.setText(valorMaximoDISK.toString() + "%");
            } else if (randomDISK < valorMinimoDISK) {
                valorMinimoDISK = randomDISK;
                lblMinNumberDISK.setText(valorMinimoDISK.toString() + "%");
            }
        }
        
        //MediaDISK
        valorMediaDISK = (randomDISK + valorMediaDISK);
        mediaAtualizadaDISK = valorMediaDISK/ rodada;
        lblMediaNumberDISK.setText(mediaAtualizadaDISK.toString() + "%");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicaoComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicaoComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicaoComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicaoComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicaoComponentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblCPUpercent;
    private javax.swing.JLabel lblDISK;
    private javax.swing.JLabel lblDISKpercent;
    private javax.swing.JLabel lblMaxCPU;
    private javax.swing.JLabel lblMaxDISK;
    private javax.swing.JLabel lblMaxNumberCPU;
    private javax.swing.JLabel lblMaxNumberDISK;
    private javax.swing.JLabel lblMaxNumberRAM;
    private javax.swing.JLabel lblMaxRAM;
    private javax.swing.JLabel lblMediaCPU;
    private javax.swing.JLabel lblMediaDISK;
    private javax.swing.JLabel lblMediaNumberCPU;
    private javax.swing.JLabel lblMediaNumberDISK;
    private javax.swing.JLabel lblMediaNumberRAM;
    private javax.swing.JLabel lblMediaRAM;
    private javax.swing.JLabel lblMinCPU;
    private javax.swing.JLabel lblMinDISK;
    private javax.swing.JLabel lblMinNumberCPU;
    private javax.swing.JLabel lblMinNumberDISK;
    private javax.swing.JLabel lblMinNumberRAM;
    private javax.swing.JLabel lblMinRAM;
    private javax.swing.JLabel lblRAM;
    private javax.swing.JLabel lblRAMpercent;
    private javax.swing.JPanel painelBackground;
    private javax.swing.JProgressBar prgCPU;
    private javax.swing.JProgressBar prgDISK;
    private javax.swing.JProgressBar prgRAM;
    // End of variables declaration//GEN-END:variables
}
