package com.tela.login.seer.view;

import com.tela.login.seer.controller.Conexao;
import com.tela.login.seer.model.Funcionario;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.springframework.jdbc.core.JdbcTemplate;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.springframework.jdbc.core.BeanPropertyRowMapper;



public class InViewLogin extends javax.swing.JFrame {

    /**
     * Creates new form InViewLogin
     */
    public InViewLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_login = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txf_email = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        pwf_senha = new javax.swing.JPasswordField();
        btn_entrar = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();
        pnl_logo = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de login");
        setBackground(new java.awt.Color(255, 199, 247));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_login.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(255, 255, 255));
        lbl_login.setText("Login");
        lbl_login.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(51, 204, 255)));
        getContentPane().add(lbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        lbl_email.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setText("E-mail");
        getContentPane().add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        txf_email.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 400, -1));

        lbl_senha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_senha.setText("Senha");
        getContentPane().add(lbl_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        pwf_senha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(pwf_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 400, -1));

        btn_entrar.setBackground(new java.awt.Color(28, 30, 32));
        btn_entrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrar.setText("Entrar");
        btn_entrar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 204, 255)));
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 230, -1));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sala-monitoramento-graficos.png"))); // NOI18N
        lbl_background.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 440, -1));

        pnl_logo.setBackground(new java.awt.Color(28, 30, 32));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InView-logo-branco.png"))); // NOI18N

        javax.swing.GroupLayout pnl_logoLayout = new javax.swing.GroupLayout(pnl_logo);
        pnl_logo.setLayout(pnl_logoLayout);
        pnl_logoLayout.setHorizontalGroup(
            pnl_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_logoLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lbl_logo)
                .addGap(38, 38, 38))
        );
        pnl_logoLayout.setVerticalGroup(
            pnl_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_logoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lbl_logo)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        validarLogin();
    }//GEN-LAST:event_btn_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //Mudança de cor da progress bar
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JPanel pnl_logo;
    private javax.swing.JPasswordField pwf_senha;
    private javax.swing.JTextField txf_email;
    // End of variables declaration//GEN-END:variables

    private void validarLogin() {  
        Conexao conexao = new Conexao();
        JdbcTemplate assistente = new JdbcTemplate(conexao.getBancoDeDados());
        
        String sql = "SELECT nome, login, senha FROM cadastro_funcionario WHERE login = ? AND senha = ?";

        List<Funcionario> resposta = assistente.query(sql, new BeanPropertyRowMapper(Funcionario.class), txf_email.getText(), pwf_senha.getText());                                                                                                 
        
        System.out.println(resposta);
        
        if(resposta.size() > 0){
            this.dispose();
            Dash telaMedicao = new Dash(resposta.get(0));
            telaMedicao.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Usuário e/ou senha incorretos");
        }
    }
}
